import assert from 'node:assert/strict'
import { buildDecisionLinks, CUISINES, parseDecisionIntent, planMeals, rankDecisions, safeDecisionUrl } from '../src/decision'
import type { DecisionCandidate, DecisionPreferences } from '../src/decisionTypes'

const base: DecisionPreferences = { kind: 'hotel', city: 'Sydney', currency: 'AUD', budgetMax: 500, seaView: false, parking: false, freeParking: false, cuisine: 'any', variety: false, minRating: 4.3, minReviews: 100, checkin: '2026-10-01', checkout: '2026-10-04', travellers: 2 }
const parse = (text: string, preferences = base) => parseDecisionIntent(text, preferences)
assert.equal(parse('想住 300 澳币以内的海景房，需要停车场').budgetMax, 300)
assert.equal(parse('想住 300 澳币以内的海景房，需要停车场').seaView, true)
assert.equal(parse('想住 300 澳币以内的海景房，需要停车场').parking, true)
assert.equal(parse('每晚预算 200–300 AUD').budgetMax, 300)
assert.equal(parse('hotel under USD 220 per night').currency, 'USD')
assert.equal(parse('每晚 800 人民币').currency, 'CNY')
assert.equal(parse('每晚 15,000 日元').budgetMax, 15000)
assert.equal(parse('每晚 15,000 日元').currency, 'JPY')
assert.equal(parse('hotel under €180').currency, 'EUR')
assert.equal(parse('不要海景，不需要停车场', { ...base, seaView: true, parking: true, freeParking: true }).seaView, false)
assert.equal(parse('不要海景，不需要停车场', { ...base, seaView: true, parking: true, freeParking: true }).parking, false)
assert.equal(parse('不要海景，不需要停车场', { ...base, seaView: true, parking: true, freeParking: true }).freeParking, false)
assert.equal(parse('sea view optional, no parking', { ...base, seaView: true, parking: true }).seaView, false)
assert.equal(parse('free parking hotel').freeParking, true)
assert.equal(parse('free parking hotel').parking, true)
assert.equal(parse('有停车场就行，免费停车无所谓', { ...base, freeParking: true }).freeParking, false)
assert.equal(parse('需要停车，不用免费停车').parking, true)
assert.equal(parse('不要停车要海景房').seaView, true)
assert.equal(parse('不要停车要海景房').parking, false)
assert.equal(parse('没有停车场').parking, false)
assert.equal(parse('不要没有停车场的酒店').parking, true)
assert.equal(parse("don't want a hotel without parking").parking, true)
assert.equal(parse('我想吃墨西哥菜，每天吃不一样的').kind, 'restaurant')
assert.equal(parse('我想吃墨西哥菜，每天吃不一样的').cuisine, 'mexican')
assert.equal(parse('我想吃墨西哥菜，每天吃不一样的').variety, true)
assert.equal(parse('Mexican restaurant under USD 40 per person').budgetMax, 40)
assert.equal(parse('Mexican restaurant under USD 40 per person').currency, 'USD')
assert.equal(parse('不要墨西哥菜，想吃日料').cuisine, 'japanese')
assert.deepEqual(parse('不要墨西哥菜，想吃日料').excludedCuisines, ['mexican'])
assert.equal(parse('不要墨西哥菜', { ...base, cuisine: 'mexican' }).cuisine, 'any')
assert.equal(parse('no Mexican, Italian food please').cuisine, 'italian')
assert.deepEqual(parse('no Mexican, Italian food please').excludedCuisines, ['mexican'])
assert.equal(parse('Mexican please', { ...base, excludedCuisines: ['mexican'] }).excludedCuisines?.length, 0)
assert.equal(parse('不要每天吃不一样', { ...base, variety: true }).variety, false)
assert.equal(parse('每天吃一样的', { ...base, variety: true }).variety, false)
assert.equal(parse('4.8 分以上，2 人，2026-10-01 入住').budgetMax, 500)
assert.equal(parse('预算300 AUD 评分4.8').budgetMax, 300)
assert.equal(parse('预算300 AUD 2026-10-01 入住').budgetMax, 300)
assert.equal(parse('墨西哥餐厅', { ...base, seaView: true, parking: true, freeParking: true }).parking, false)
assert.equal(parse('墨西哥餐厅需要免费停车', { ...base, seaView: true, parking: true, freeParking: true }).parking, true)
assert.equal(parse('酒店', { ...base, kind: 'restaurant', cuisine: 'mexican', variety: true }).cuisine, 'any')
assert.equal(parse('酒店', { ...base, kind: 'restaurant', cuisine: 'mexican', variety: true }).variety, false)
const englishHotel = parse('An ocean-view room under AUD 300 per night with free parking', { ...base, kind: 'restaurant', budgetMax: 50, cuisine: 'mexican', variety: true })
assert.equal(englishHotel.kind, 'hotel')
assert.equal(englishHotel.budgetMax, 300)
assert.equal(englishHotel.seaView, true)
assert.equal(englishHotel.parking, true)
assert.equal(englishHotel.freeParking, true)
assert.equal(englishHotel.variety, false)
assert.equal(englishHotel.cuisine, 'any')
assert.equal(parse('A room under AUD 200', { ...base, kind: 'restaurant' }).kind, 'hotel')
assert.equal(parse('under AUD 200 per night', { ...base, kind: 'restaurant' }).kind, 'hotel')
assert.equal(parse('Mexican restaurant with a dining room under AUD 50 per person').kind, 'restaurant')
assert.equal(parse('A restaurant dining room with free parking').kind, 'restaurant')
assert.equal(parse('每晚预算 -300 AUD').budgetMax, 500)
assert.equal(parse('每晚预算 300-200 AUD').budgetMax, 500)
assert.equal(parse('每晚预算 0 AUD').budgetMax, 500)
assert.equal(parse('每晚预算 Infinity AUD').budgetMax, 500)
assert.equal(parse('每晚预算300.123 AUD').budgetMax, 500)
assert.equal(parse('每晚预算1e3 AUD').budgetMax, 500)
assert.equal(parse('每晚预算AUD200-USD300').budgetMax, 500)
assert.equal(parse('每晚 300 CAD').budgetMax, 500)
assert.equal(parse('预算至少 300 AUD').budgetMax, 500)
assert.equal(parse('预算不要超过 300 AUD').budgetMax, 300)
assert.equal(parse('hotel 每人预算 300 AUD').budgetMax, 500)
assert.equal(parse('want a balcony and quiet neighbourhood').budgetMax, 500)
assert.equal(parse('want a balcony and quiet neighbourhood').kind, base.kind)
assert.equal(base.seaView, false, 'parser must not mutate input')

function hotel(id: string, overrides: Partial<DecisionCandidate> = {}): DecisionCandidate {
  return { id, kind: 'hotel', name: `Hotel ${id}`, city: 'Sydney', source: 'curated', sourceUrl: 'https://hotel.example/about', price: { max: 250, currency: 'AUD', basis: 'night' }, seaView: 'room', parking: 'free', rating: { value: 4.6, count: 1000, sourceUrl: 'https://maps.google.com/reviews' }, ...overrides }
}
const strict = { ...base, budgetMax: 300, seaView: true, parking: true, freeParking: true }
const ranked = rankDecisions([
  hotel('match'), hotel('expensive', { price: { min: 200, max: 301, currency: 'AUD', basis: 'night' } }),
  hotel('foreign', { price: { max: 100, currency: 'USD', basis: 'night' } }),
  hotel('wrong-unit', { price: { max: 100, currency: 'AUD', basis: 'person' } }),
  hotel('property-view', { seaView: 'property' }), hotel('no-view', { seaView: 'none' }),
  hotel('paid-parking', { parking: 'paid' }), hotel('few-reviews', { rating: { value: 5, count: 2, sourceUrl: 'https://ratings.example' } }),
  hotel('no-reviews', { rating: { value: 5, sourceUrl: 'https://ratings.example' } }), hotel('bad-rating', { rating: { value: 9, count: 500, sourceUrl: 'https://ratings.example' } }),
  hotel('unknown', { rating: undefined, parking: undefined, seaView: undefined, price: undefined }),
  hotel('other-city', { city: 'Melbourne' }), hotel('restaurant', { kind: 'restaurant' }),
], strict)
const get = (id: string) => ranked.find((result) => result.candidate.id === id)!
assert.equal(ranked[0].candidate.id, 'match')
assert.equal(get('match').confidence, 'confirmed')
assert.equal(get('match').matchScore, 100)
assert.equal(get('expensive').confidence, 'excluded')
assert.equal(get('no-view').confidence, 'excluded')
assert.equal(get('paid-parking').confidence, 'excluded')
assert.equal(get('few-reviews').confidence, 'excluded')
for (const id of ['foreign', 'wrong-unit', 'property-view', 'no-reviews', 'bad-rating', 'unknown']) {
  assert.equal(get(id).confidence, 'check', id)
  assert.ok(get(id).matchScore <= 69, id)
}
assert.equal(get('unknown').matchScore, 0)
assert.equal(get('no-reviews').qualityScore, 0)
assert.equal(get('bad-rating').qualityScore, 0)
assert.ok(!ranked.some((result) => ['other-city', 'restaurant'].includes(result.candidate.id)))
assert.ok(get('match').qualityScore > get('few-reviews').qualityScore)
assert.equal(rankDecisions([hotel('sydney')], { ...base, city: '悉尼' }).length, 1)
assert.equal(rankDecisions([hotel('melb', { city: 'Melbourne, Australia' })], { ...base, city: '墨尔本' }).length, 1)
assert.equal(rankDecisions([hotel('sydney')], { ...base, city: 'North Sydney' }).length, 1)
assert.equal(rankDecisions([hotel('springfield', { city: 'Springfield' })], { ...base, city: 'Springfield Heights' }).length, 0)
assert.equal(rankDecisions([hotel('duplicate'), hotel('duplicate2', { name: 'Hotel duplicate' })], base).length, 1)
assert.equal(rankDecisions([hotel('duplicate'), hotel('google', { name: 'Hotel duplicate', source: 'google' })], base)[0].candidate.id, 'google')
assert.equal(rankDecisions([hotel('a', { name: 'Chain', address: '1 First St' }), hotel('b', { name: 'Chain', address: '2 Second St' })], base).length, 2)
assert.equal(rankDecisions([hotel('empty-city', { city: '' })], base).length, 0)
assert.equal(rankDecisions([hotel('empty-city', { city: '' })], { ...base, city: '' }).length, 0)
assert.equal(rankDecisions([hotel('canggu', { city: 'Canggu, Bali' }), hotel('ubud', { city: 'Ubud' })], { ...base, city: 'Bali' }).length, 2)
assert.equal(rankDecisions([hotel('bali', { city: 'Bali' }), hotel('ubud', { city: 'Ubud' }), hotel('canggu', { city: 'Canggu, Bali' })], { ...base, city: 'Canggu' }).length, 1)
assert.equal(rankDecisions([hotel('canggu', { city: 'Canggu, Bali' })], { ...base, city: '仓古' }).length, 1)
assert.equal(rankDecisions([hotel('boundary', { price: { max: 300, currency: 'AUD', basis: 'night' } })], strict)[0].confidence, 'confirmed')
assert.equal(rankDecisions([hotel('zero', { price: { max: 0, currency: 'AUD', basis: 'night' } })], strict)[0].criteria.find((criterion) => criterion.key === 'budget')?.state, 'unknown')
assert.equal(rankDecisions([hotel('invalid-range', { price: { min: 400, max: 200, currency: 'AUD', basis: 'night' } })], strict)[0].criteria.find((criterion) => criterion.key === 'budget')?.state, 'unknown')
assert.equal(rankDecisions([hotel('saved', { source: 'saved' })], base)[0].candidate.source, 'saved')

function restaurant(id: string, cuisines: DecisionCandidate['cuisines'], city = 'Sydney'): DecisionCandidate {
  return { id, kind: 'restaurant', name: `Restaurant ${id}`, city, cuisines, source: 'curated', sourceUrl: 'https://restaurant.example', rating: { value: 4.7, count: 700, sourceUrl: 'https://ratings.example' }, price: { max: 35, currency: 'AUD', basis: 'person' } }
}
const foodPrefs: DecisionPreferences = { ...base, kind: 'restaurant', budgetMax: 40, cuisine: 'mexican', variety: true }
const restaurants = [restaurant('mex1', ['mexican']), restaurant('mex2', ['mexican']), restaurant('japan1', ['japanese']), restaurant('italian1', ['italian']), restaurant('thai-melb', ['thai'], 'Melbourne')]
assert.equal(rankDecisions(restaurants, foodPrefs).find((item) => item.candidate.id === 'japan1')?.confidence, 'excluded')
assert.equal(rankDecisions([restaurant('unknown', undefined)], foodPrefs)[0].confidence, 'check')
assert.equal(rankDecisions(restaurants, { ...foodPrefs, cuisine: 'any', excludedCuisines: ['mexican'] }).find((item) => item.candidate.id === 'mex1')?.confidence, 'excluded')
const days = [{ date: '2026-10-01', city: 'Sydney' }, { date: '2026-10-02', city: 'Sydney' }, { date: '2026-10-03', city: 'Melbourne' }, { date: '2026-10-04', city: 'Melbourne' }]
const meals = planMeals(days, foodPrefs, restaurants)
assert.deepEqual(meals.map((meal) => meal.date), days.map((day) => day.date))
assert.equal(meals[0].cuisine, 'mexican')
assert.equal(meals[0].candidate?.id, 'mex1')
assert.equal(meals[1].cuisine, 'italian')
assert.equal(meals[2].cuisine, 'thai')
assert.equal(meals[2].candidate?.city, 'Melbourne')
assert.equal(meals[3].candidate, undefined)
assert.equal(new Set(meals.map((meal) => meal.cuisine)).size, 4)
assert.ok(meals.every((meal) => !meal.repeated))
const offline = planMeals(days, foodPrefs, [])
assert.deepEqual(offline.map((meal) => meal.cuisine), ['mexican', 'japanese', 'italian', 'thai'])
assert.ok(offline.every((meal) => !meal.candidate))
const repeatedIntent = planMeals(days.slice(0, 2), { ...foodPrefs, variety: false }, restaurants)
assert.deepEqual(repeatedIntent.map((meal) => meal.candidate?.id), ['mex1', 'mex2'])
const used = planMeals(days.slice(0, 1), foodPrefs, restaurants, [{ ...meals[0] }])
assert.equal(used[0].candidate?.id, 'mex1')
assert.equal(used[0].repeated, false)
assert.deepEqual(used[0], meals[0])
const withoutMexican = planMeals(days, { ...foodPrefs, excludedCuisines: ['mexican'] }, restaurants)
assert.ok(withoutMexican.every((meal) => meal.cuisine !== 'mexican'))
assert.ok(withoutMexican.every((meal) => !meal.candidate?.cuisines?.includes('mexican')))
const manyDays = Array.from({ length: 12 }, (_, index) => ({ date: `2026-10-${String(index + 1).padStart(2, '0')}`, city: 'Sydney' }))
const longTrip = planMeals(manyDays, foodPrefs, [])
assert.ok(longTrip.slice(0, 9).every((meal) => !meal.repeated))
assert.ok(longTrip.slice(9).every((meal) => meal.repeated))
const selectedFirst = { ...meals[0], repeated: true }
const tripWithFirst = planMeals(manyDays.slice(0, 10), foodPrefs, [], [selectedFirst])
assert.equal(tripWithFirst[0].candidate?.id, selectedFirst.candidate?.id)
assert.equal(tripWithFirst[0].repeated, false)
assert.equal(new Set(tripWithFirst.slice(0, 9).map((meal) => meal.cuisine)).size, 9)
assert.equal(tripWithFirst.filter((meal) => meal.repeated).length, 1)
const selectedFuture = { ...meals[0], date: manyDays[8].date, city: 'Melbourne', repeated: true }
const tripWithFuture = planMeals(manyDays.slice(0, 10), foodPrefs, [], [selectedFuture])
assert.equal(tripWithFuture[8].candidate?.id, selectedFuture.candidate?.id)
assert.equal(tripWithFuture[8].city, 'Melbourne')
assert.equal(tripWithFuture[8].repeated, false)
assert.ok(tripWithFuture.slice(0, 8).every((meal) => meal.cuisine !== 'mexican'))
assert.equal(new Set(tripWithFuture.slice(0, 9).map((meal) => meal.cuisine)).size, 9)
assert.equal(tripWithFuture.filter((meal) => meal.repeated).length, 1)
const trueRepeat = planMeals(days.slice(0, 2), foodPrefs, restaurants, [meals[0], { ...meals[0], date: days[1].date }])
assert.deepEqual(trueRepeat.map((meal) => meal.repeated), [false, true])
const reverseDays = planMeals([...days.slice(0, 2)].reverse(), foodPrefs, [], [meals[0], { ...meals[0], date: days[1].date }])
assert.deepEqual(reverseDays.map((meal) => meal.date), [days[1].date, days[0].date])
assert.deepEqual(reverseDays.map((meal) => meal.repeated), [true, false])
const selectedHistory = planMeals(days.slice(0, 1), foodPrefs, [], [{ ...meals[0], date: '2026-09-30' }])
assert.equal(selectedHistory[0].cuisine, 'japanese')
assert.equal(selectedHistory[0].repeated, false)
assert.equal(planMeals([{ date: '2026-02-30', city: 'Sydney' }, days[0], days[0]], foodPrefs, []).length, 1)
assert.equal(planMeals(days, { ...foodPrefs, excludedCuisines: [...CUISINES] }, restaurants)[0].candidate, undefined)

for (const unsafe of ['javascript:alert(1)', 'data:text/html,hello', 'file:///etc/passwd', '//example.com', 'https://user:password@example.com', 'https://example.com\n/path', 'not a URL']) assert.equal(safeDecisionUrl(unsafe), undefined)
assert.equal(safeDecisionUrl('https://example.com/book?q=test'), 'https://example.com/book?q=test')
assert.equal(safeDecisionUrl('http://example.com'), 'http://example.com/')
const links = buildDecisionLinks(strict, hotel('safe', { websiteUrl: 'javascript:alert(1)', bookingUrl: 'https://user:pass@example.com' }))
assert.ok(links.every((link) => safeDecisionUrl(link.url)))
assert.ok(!links.some((link) => link.kind === 'booking'))
const bookingSearch = new URL(links.find((link) => link.url.startsWith('https://www.booking.com/'))!.url)
assert.equal(bookingSearch.searchParams.get('ss'), 'Hotel safe Sydney')
assert.equal(bookingSearch.searchParams.get('checkin'), base.checkin)
assert.equal(bookingSearch.searchParams.get('checkout'), base.checkout)
assert.equal(bookingSearch.searchParams.get('group_adults'), '2')
assert.equal(bookingSearch.searchParams.get('selected_currency'), 'AUD')
assert.equal(bookingSearch.searchParams.get('nflt'), null)
const genericSearch = new URL(buildDecisionLinks(strict).find((link) => link.label.includes('条件'))!.url)
assert.ok(genericSearch.searchParams.get('q')?.includes('sea view room'))
assert.ok(genericSearch.searchParams.get('q')?.includes('free parking'))
assert.ok(genericSearch.searchParams.get('q')?.includes('under AUD 300 per night'))
const badDates = buildDecisionLinks({ ...base, checkin: '2026-02-30', checkout: '2026-02-29', travellers: -1 })
const badBooking = new URL(badDates.find((link) => link.url.startsWith('https://www.booking.com/'))!.url)
assert.equal(badBooking.searchParams.get('checkin'), null)
assert.equal(badBooking.searchParams.get('group_adults'), null)
const restaurantLinks = buildDecisionLinks(foodPrefs, restaurant('mex1', ['mexican']))
assert.ok(restaurantLinks.some((link) => link.kind === 'search' && link.label.includes('订位')))
assert.ok(!restaurantLinks.some((link) => link.kind === 'booking'))
const directBooking = buildDecisionLinks(foodPrefs, { ...restaurant('mex1', ['mexican']), bookingUrl: 'https://restaurant.example/book' })
assert.equal(directBooking.find((link) => link.kind === 'booking')?.url, 'https://restaurant.example/book')
const sameBooking = buildDecisionLinks(foodPrefs, { ...restaurant('mex1', ['mexican']), websiteUrl: 'https://restaurant.example/book', bookingUrl: 'https://restaurant.example/book' })
assert.equal(sameBooking.find((link) => link.kind === 'booking')?.url, 'https://restaurant.example/book')

console.log('decision tests passed')
