import type { DayPlan, PlaceStop, Trip, WeatherSnap } from './types'
import { uid } from './lib'

function w(
  condition: WeatherSnap['condition'],
  tMin: number,
  tMax: number,
  rainProb: number,
  extra: Partial<WeatherSnap> = {},
): WeatherSnap {
  const summary =
    rainProb >= 70
      ? '大概率下雨，户外行程建议备 Plan B'
      : rainProb >= 40
        ? '有阵雨可能，随身带伞'
        : condition === 'sunny'
          ? '适合户外走走'
          : '天气尚可'
  return { condition, tMin, tMax, rainProb, summary, ...extra }
}

function p(partial: Omit<PlaceStop, 'id'>): PlaceStop {
  return { id: uid(), ...partial }
}

function day(partial: Omit<DayPlan, 'id'>): DayPlan {
  return { id: uid(), ...partial }
}

export function japanTrip(): Trip {
  const days: DayPlan[] = [
    day({
      date: '2026-09-25',
      city: 'Tokyo',
      stay: 'Hotel Gracery Shinjuku',
      transportMode: 'public',
      weather: w('cloudy', 19, 25, 20),
      activePlan: 'A',
      planA: [
        p({
          name: '抵达羽田机场',
          category: '交通',
          setting: 'indoor',
          time: '15:40',
          durationMin: 60,
          notes: 'JQ 23 墨尔本直飞',
          transportToNext: 'public',
          coords: { lat: 35.5494, lng: 139.7798 },
        }),
        p({
          name: '入住新宿',
          category: '住宿',
          setting: 'indoor',
          time: '18:00',
          durationMin: 40,
          notes: 'Hotel Gracery Shinjuku · 已订',
          booked: true,
          coords: { lat: 35.6946, lng: 139.7015 },
        }),
        p({
          name: '一兰拉面 新宿',
          category: '餐饮',
          setting: 'indoor',
          time: '19:30',
          durationMin: 50,
          cost: { amount: 24, currency: 'AUD', status: 'estimated' },
          coords: { lat: 35.6938, lng: 139.7014 },
        }),
      ],
      planB: [
        p({
          name: '机场到酒店直达',
          category: '交通',
          setting: 'indoor',
          time: '16:00',
          notes: '下雨就打车，少走换乘',
          transportToNext: 'taxi',
        }),
        p({
          name: '酒店附近随便吃',
          category: '餐饮',
          setting: 'indoor',
          time: '19:00',
        }),
      ],
    }),
    day({
      date: '2026-09-26',
      city: 'Tokyo',
      stay: 'Hotel Gracery Shinjuku',
      transportMode: 'public',
      weather: w('sunny', 18, 26, 10),
      activePlan: 'A',
      planA: [
        p({
          name: '早餐',
          category: '餐饮',
          setting: 'indoor',
          time: '09:00',
          durationMin: 45,
          coords: { lat: 35.6946, lng: 139.7015 },
        }),
        p({
          name: '明治神宫',
          category: '景点',
          setting: 'outdoor',
          time: '10:00',
          durationMin: 90,
          priority: 'must',
          transportToNext: 'walking',
          coords: { lat: 35.6764, lng: 139.6993 },
        }),
        p({
          name: '原宿 Takeshita',
          category: '购物',
          setting: 'mixed',
          time: '12:00',
          durationMin: 90,
          priority: 'want',
          coords: { lat: 35.6702, lng: 139.7026 },
        }),
        p({
          name: '涩谷十字路口',
          category: '景点',
          setting: 'outdoor',
          time: '14:00',
          durationMin: 40,
          transportToNext: 'walking',
          coords: { lat: 35.6595, lng: 139.7004 },
        }),
        p({
          name: 'Shibuya Sky',
          category: '景点',
          setting: 'mixed',
          time: '16:00',
          durationMin: 80,
          priority: 'must',
          ticketNeeded: true,
          ticketUrl: 'https://www.shibuya-sky.com/',
          booked: true,
          cost: { amount: 36, currency: 'AUD', status: 'paid' },
          coords: { lat: 35.658, lng: 139.7026 },
        }),
        p({
          name: '晚饭 · 涩谷',
          category: '餐饮',
          setting: 'indoor',
          time: '19:00',
          durationMin: 90,
          cost: { amount: 70, currency: 'AUD', status: 'estimated' },
          coords: { lat: 35.659, lng: 139.698 },
        }),
      ],
      planB: [
        p({
          name: 'TeamLab Planets',
          category: '活动',
          setting: 'indoor',
          time: '10:00',
          durationMin: 150,
          ticketNeeded: true,
          priority: 'must',
          coords: { lat: 35.649, lng: 139.79 },
        }),
        p({
          name: '涩谷 PARCO',
          category: '购物',
          setting: 'indoor',
          time: '14:00',
          durationMin: 90,
          coords: { lat: 35.6618, lng: 139.6983 },
        }),
        p({
          name: '午饭买手店随便逛',
          category: '餐饮',
          setting: 'indoor',
          time: '16:30',
        }),
      ],
    }),
    day({
      date: '2026-09-27',
      city: 'Tokyo',
      stay: 'Hotel Gracery Shinjuku',
      transportMode: 'public',
      weather: w('cloudy', 17, 24, 35),
      activePlan: 'A',
      planA: [
        p({
          name: '浅草寺',
          category: '景点',
          setting: 'outdoor',
          time: '09:30',
          durationMin: 80,
          priority: 'must',
          coords: { lat: 35.7148, lng: 139.7967 },
        }),
        p({
          name: '仲见世通',
          category: '购物',
          setting: 'outdoor',
          time: '11:00',
          durationMin: 50,
          coords: { lat: 35.7117, lng: 139.7963 },
        }),
        p({
          name: '东京国立博物馆',
          category: '景点',
          setting: 'indoor',
          time: '13:30',
          durationMin: 120,
          ticketNeeded: true,
          coords: { lat: 35.7188, lng: 139.7765 },
        }),
        p({
          name: '上野公园散步',
          category: '景点',
          setting: 'outdoor',
          time: '16:00',
          durationMin: 60,
          coords: { lat: 35.7148, lng: 139.7714 },
        }),
      ],
      planB: [
        p({
          name: '东京国立博物馆',
          category: '景点',
          setting: 'indoor',
          time: '10:00',
          durationMin: 150,
          coords: { lat: 35.7188, lng: 139.7765 },
        }),
        p({
          name: 'Ameyoko 地下吃喝',
          category: '餐饮',
          setting: 'mixed',
          time: '13:00',
          coords: { lat: 35.7107, lng: 139.7745 },
        }),
        p({
          name: 'Sunshine City 水族馆',
          category: '景点',
          setting: 'indoor',
          time: '15:30',
          ticketNeeded: true,
          coords: { lat: 35.729, lng: 139.7198 },
        }),
      ],
    }),
    day({
      date: '2026-09-28',
      city: 'Fuji',
      stay: 'Kawaguchiko lakeside',
      transportMode: 'self-drive',
      weather: w('sunny', 12, 21, 15),
      activePlan: 'A',
      notes: '新宿取车 → 河口湖。沿途可停忍野八海。',
      planA: [
        p({
          name: '新宿取车',
          category: '交通',
          setting: 'indoor',
          time: '08:30',
          booked: true,
          transportToNext: 'self-drive',
          coords: { lat: 35.6909, lng: 139.7003 },
        }),
        p({
          name: '忍野八海',
          category: '景点',
          setting: 'outdoor',
          time: '11:00',
          durationMin: 70,
          priority: 'want',
          notes: '绕路约 +18 min',
          coords: { lat: 35.4606, lng: 138.8278 },
        }),
        p({
          name: '河口湖观景',
          category: '景点',
          setting: 'outdoor',
          time: '14:00',
          durationMin: 90,
          priority: 'must',
          coords: { lat: 35.517, lng: 138.755 },
        }),
        p({
          name: '富士山全景缆车',
          category: '活动',
          setting: 'mixed',
          time: '16:00',
          durationMin: 60,
          ticketNeeded: true,
          coords: { lat: 35.5015, lng: 138.766 },
        }),
      ],
      planB: [
        p({
          name: '火车前往河口湖',
          category: '交通',
          setting: 'indoor',
          time: '08:40',
          transportToNext: 'public',
        }),
        p({
          name: '富士山世界遗产中心',
          category: '景点',
          setting: 'indoor',
          time: '13:00',
          coords: { lat: 35.459, lng: 138.801 },
        }),
      ],
    }),
    day({
      date: '2026-09-29',
      city: 'Kyoto',
      stay: 'Hotel Resol Kyoto Shijo Kawaramachi',
      transportMode: 'mixed',
      weather: w('cloudy', 16, 23, 40),
      activePlan: 'A',
      planA: [
        p({
          name: '还车 · 小田原 / 京都方向',
          category: '交通',
          setting: 'mixed',
          time: '09:00',
          durationMin: 180,
          transportToNext: 'self-drive',
          coords: { lat: 35.256, lng: 139.155 },
        }),
        p({
          name: '新干线到京都',
          category: '交通',
          setting: 'indoor',
          time: '13:00',
          booked: true,
          ticketNeeded: true,
          transportToNext: 'public',
          coords: { lat: 34.9858, lng: 135.7588 },
        }),
        p({
          name: '先斗町散步晚饭',
          category: '餐饮',
          setting: 'outdoor',
          time: '18:30',
          coords: { lat: 35.007, lng: 135.771 },
        }),
      ],
      planB: [
        p({
          name: '整天火车：河口湖 → 京都',
          category: '交通',
          setting: 'indoor',
          time: '09:00',
          transportToNext: 'public',
        }),
      ],
    }),
    day({
      date: '2026-09-30',
      city: 'Kyoto',
      stay: 'Hotel Resol Kyoto Shijo Kawaramachi',
      transportMode: 'public',
      weather: w('rain', 18, 22, 80, { rainWindow: '10:00–16:00' }),
      activePlan: 'A',
      notes: '这一天是天气备选的示范：户外东山 vs 室内博物馆。',
      planA: [
        p({
          name: '伏见稻荷大社',
          category: '景点',
          setting: 'outdoor',
          time: '09:00',
          durationMin: 120,
          priority: 'must',
          coords: { lat: 34.9671, lng: 135.7727 },
        }),
        p({
          name: '清水寺',
          category: '景点',
          setting: 'outdoor',
          time: '12:30',
          durationMin: 90,
          priority: 'must',
          ticketNeeded: true,
          coords: { lat: 34.9949, lng: 135.785 },
        }),
        p({
          name: '二年坂 / 三年坂',
          category: '景点',
          setting: 'outdoor',
          time: '14:30',
          durationMin: 60,
          coords: { lat: 34.9965, lng: 135.7825 },
        }),
        p({
          name: '祇园',
          category: '景点',
          setting: 'outdoor',
          time: '16:30',
          durationMin: 70,
          coords: { lat: 35.0036, lng: 135.7784 },
        }),
        p({
          name: '怀石或京料理',
          category: '餐饮',
          setting: 'indoor',
          time: '19:00',
          cost: { amount: 160, currency: 'AUD', status: 'estimated' },
          coords: { lat: 35.003, lng: 135.77 },
        }),
      ],
      planB: [
        p({
          name: '京都铁道博物馆',
          category: '景点',
          setting: 'indoor',
          time: '09:30',
          durationMin: 120,
          ticketNeeded: true,
          coords: { lat: 34.9873, lng: 135.7441 },
        }),
        p({
          name: '锦市场吃喝',
          category: '餐饮',
          setting: 'mixed',
          time: '12:30',
          durationMin: 70,
          coords: { lat: 35.005, lng: 135.7647 },
        }),
        p({
          name: '京都国立博物馆',
          category: '景点',
          setting: 'indoor',
          time: '14:30',
          durationMin: 100,
          coords: { lat: 34.9901, lng: 135.773 },
        }),
        p({
          name: 'Aeon / 地下街购物',
          category: '购物',
          setting: 'indoor',
          time: '17:00',
        }),
      ],
    }),
    day({
      date: '2026-10-01',
      city: 'Kyoto',
      stay: 'Hotel Resol Kyoto Shijo Kawaramachi',
      transportMode: 'public',
      weather: w('sunny', 17, 24, 20),
      activePlan: 'A',
      planA: [
        p({
          name: '岚山竹林',
          category: '景点',
          setting: 'outdoor',
          time: '09:00',
          durationMin: 50,
          priority: 'must',
          coords: { lat: 35.017, lng: 135.672 },
        }),
        p({
          name: '天龙寺',
          category: '景点',
          setting: 'outdoor',
          time: '10:00',
          durationMin: 70,
          coords: { lat: 35.0159, lng: 135.6736 },
        }),
        p({
          name: '渡月桥',
          category: '景点',
          setting: 'outdoor',
          time: '12:00',
          coords: { lat: 35.0126, lng: 135.6778 },
        }),
        p({
          name: '金阁寺',
          category: '景点',
          setting: 'outdoor',
          time: '15:00',
          durationMin: 60,
          priority: 'must',
          ticketNeeded: true,
          coords: { lat: 35.0394, lng: 135.7292 },
        }),
      ],
      planB: [
        p({
          name: '二条城（室内展厅多）',
          category: '景点',
          setting: 'mixed',
          time: '10:00',
          coords: { lat: 35.0142, lng: 135.7482 },
        }),
        p({
          name: '京都国际漫画博物馆',
          category: '景点',
          setting: 'indoor',
          time: '14:00',
          coords: { lat: 35.0104, lng: 135.7598 },
        }),
      ],
    }),
    day({
      date: '2026-10-02',
      city: 'Osaka',
      stay: 'Cross Hotel Osaka',
      transportMode: 'public',
      weather: w('cloudy', 19, 26, 25),
      activePlan: 'A',
      planA: [
        p({
          name: '新干线京都 → 大阪',
          category: '交通',
          setting: 'indoor',
          time: '09:30',
          booked: true,
          transportToNext: 'public',
          coords: { lat: 34.7024, lng: 135.4959 },
        }),
        p({
          name: '大阪城',
          category: '景点',
          setting: 'mixed',
          time: '11:00',
          durationMin: 90,
          ticketNeeded: true,
          coords: { lat: 34.6873, lng: 135.5262 },
        }),
        p({
          name: '心斋桥 / 道顿堀',
          category: '购物',
          setting: 'outdoor',
          time: '15:00',
          durationMin: 150,
          coords: { lat: 34.6687, lng: 135.5013 },
        }),
        p({
          name: '章鱼烧 + 晚饭',
          category: '餐饮',
          setting: 'outdoor',
          time: '18:30',
          cost: { amount: 55, currency: 'AUD', status: 'estimated' },
        }),
      ],
      planB: [
        p({
          name: '海游馆',
          category: '景点',
          setting: 'indoor',
          time: '10:30',
          ticketNeeded: true,
          coords: { lat: 34.6545, lng: 135.4289 },
        }),
        p({
          name: '梅田空中庭园',
          category: '景点',
          setting: 'indoor',
          time: '15:00',
          coords: { lat: 34.7053, lng: 135.4904 },
        }),
      ],
    }),
    day({
      date: '2026-10-03',
      city: 'Osaka',
      stay: 'Cross Hotel Osaka',
      transportMode: 'public',
      weather: w('sunny', 18, 25, 15),
      activePlan: 'A',
      planA: [
        p({
          name: '奈良一日',
          category: '景点',
          setting: 'outdoor',
          time: '09:00',
          durationMin: 360,
          priority: 'want',
          notes: 'JR 约 50 分钟',
          coords: { lat: 34.6851, lng: 135.843 },
        }),
        p({
          name: '东大寺 / 鹿',
          category: '景点',
          setting: 'outdoor',
          time: '10:30',
          coords: { lat: 34.689, lng: 135.8398 },
        }),
        p({
          name: '回大阪买伴手礼',
          category: '购物',
          setting: 'indoor',
          time: '17:00',
          coords: { lat: 34.676, lng: 135.5 },
        }),
      ],
      planB: [
        p({
          name: 'USJ（若下雨改室内项目）',
          category: '活动',
          setting: 'mixed',
          time: '09:00',
          ticketNeeded: true,
          coords: { lat: 34.6654, lng: 135.4323 },
        }),
      ],
    }),
    day({
      date: '2026-10-04',
      city: 'Osaka',
      stay: '返程',
      transportMode: 'flight',
      weather: w('cloudy', 18, 24, 30),
      activePlan: 'A',
      planA: [
        p({
          name: '关西机场',
          category: '交通',
          setting: 'indoor',
          time: '10:00',
          notes: '回墨尔本，预留 3 小时',
          coords: { lat: 34.434, lng: 135.232 },
        }),
      ],
      planB: [],
    }),
  ]

  return {
    id: 'japan-2026',
    name: 'Japan 2026',
    origin: 'Melbourne',
    destinations: ['Tokyo', 'Fuji', 'Kyoto', 'Osaka'],
    startDate: '2026-09-25',
    endDate: '2026-10-04',
    travellers: 2,
    members: [
      { id: 'm-a', name: 'Ari', role: 'owner', color: '#D989A0' },
      { id: 'm-b', name: 'Bo', role: 'editor', color: '#3E8EBE' },
    ],
    budgetPerPerson: 3500,
    totalBudget: 7000,
    homeCurrency: 'AUD',
    theme: 'cream',
    cover: 'tokyo',
    transportModes: ['public', 'self-drive', 'walking'],
    days,
    saved: [
      {
        id: 'sv-f1',
        kind: 'flight',
        name: 'Jetstar JQ23',
        subtitle: 'MEL → HND · 25 Sep 07:00–15:40',
        status: 'booked',
        price: { amount: 629, currency: 'AUD' },
        url: 'https://www.skyscanner.com.au/',
        notes: '直飞，托运行李另算',
        pros: ['直飞', '白天到达'],
        cons: ['廉航', '座位窄'],
        votes: { 'm-a': true, 'm-b': true },
        watchTarget: 550,
        priceHistory: [
          { date: '2026-04-02', amount: 710 },
          { date: '2026-05-18', amount: 668 },
          { date: '2026-06-21', amount: 629 },
        ],
        meta: { airline: 'Jetstar', bags: '7kg + 20kg', refund: '不可退' },
      },
      {
        id: 'sv-f2',
        kind: 'flight',
        name: 'JAL JL772',
        subtitle: 'MEL → NRT · 1 次转机',
        status: 'rejected',
        price: { amount: 1180, currency: 'AUD' },
        rejectReason: '贵太多，而且到成田还要再转',
        votes: { 'm-a': false, 'm-b': false },
        meta: { airline: 'JAL', bags: '2×23kg', refund: '可改期' },
      },
      {
        id: 'sv-h1',
        kind: 'hotel',
        name: 'Hotel Gracery Shinjuku',
        subtitle: '新宿 · 哥斯拉头 · 3 晚',
        status: 'booked',
        price: { amount: 268, currency: 'AUD' },
        rating: 8.4,
        notes: '如果低于 A$180 再纠结其他家——已经订了就别翻了',
        pros: ['地铁近', '附近吃饭方便', '有点好玩'],
        cons: ['房间偏小'],
        votes: { 'm-a': true, 'm-b': true },
        meta: { breakfast: '无', parking: '无', cancel: '不可取消', size: '18㎡' },
      },
      {
        id: 'sv-h2',
        kind: 'hotel',
        name: 'Mitsui Garden Shiodome',
        subtitle: '汐留 · 3 晚',
        status: 'rejected',
        price: { amount: 245, currency: 'AUD' },
        rating: 8.6,
        rejectReason: '离车站步行偏远，晚上回酒店不方便',
        votes: { 'm-a': false },
        cons: ['离地铁远'],
        meta: { breakfast: '有', parking: '收费', cancel: '免费取消', size: '22㎡' },
      },
      {
        id: 'sv-h3',
        kind: 'hotel',
        name: 'Hotel Resol Kyoto Shijo',
        subtitle: '四条河原町 · 3 晚',
        status: 'shortlisted',
        price: { amount: 198, currency: 'AUD' },
        rating: 8.7,
        pros: ['位置极好', '早餐评价高'],
        cons: ['房间小'],
        notes: '如果价格 < A$180 就定它',
        votes: { 'm-a': true, 'm-b': true },
        meta: { breakfast: '有', parking: '无', cancel: '24h 前免费', size: '16㎡' },
      },
      {
        id: 'sv-h4',
        kind: 'hotel',
        name: 'Cross Hotel Osaka',
        subtitle: '道顿堀旁边 · 2 晚',
        status: 'comparing',
        price: { amount: 220, currency: 'AUD' },
        rating: 8.8,
        pros: ['夜景', '走路就是道顿堀'],
        cons: ['周末贵'],
        votes: { 'm-a': true },
        meta: { breakfast: '有', parking: '无', cancel: '可取消', size: '24㎡' },
      },
      {
        id: 'sv-r1',
        kind: 'restaurant',
        name: '菊乃井',
        subtitle: '京都怀石',
        status: 'interested',
        price: { amount: 280, currency: 'AUD' },
        notes: '要不要考虑午餐会席，便宜一半',
        votes: {},
      },
      {
        id: 'sv-a1',
        kind: 'activity',
        name: 'Shibuya Sky',
        subtitle: '16:00 日落场',
        status: 'booked',
        price: { amount: 36, currency: 'AUD' },
        votes: { 'm-a': true, 'm-b': true },
      },
      {
        id: 'sv-a2',
        kind: 'activity',
        name: 'TeamLab Planets',
        subtitle: '雨天 Plan B',
        status: 'shortlisted',
        price: { amount: 58, currency: 'AUD' },
        votes: { 'm-b': true },
      },
      {
        id: 'sv-c1',
        kind: 'rental-car',
        name: 'Toyota Compact · 新宿取 / 小田原还',
        subtitle: '9/28–9/29',
        status: 'booked',
        price: { amount: 186, currency: 'AUD' },
        votes: {},
      },
    ],
    compares: [
      {
        id: 'cmp-hotel-tokyo',
        kind: 'hotel',
        title: '东京住哪',
        itemIds: ['sv-h1', 'sv-h2'],
      },
      {
        id: 'cmp-flight',
        kind: 'flight',
        title: '去程机票',
        itemIds: ['sv-f1', 'sv-f2'],
      },
      {
        id: 'cmp-hotel-osa',
        kind: 'hotel',
        title: '大阪住哪',
        itemIds: ['sv-h4'],
      },
    ],
    bookings: [
      {
        id: 'bk-1',
        kind: 'flight',
        name: 'JQ23 MEL → HND',
        status: 'paid',
        date: '2026-09-25',
        confirmation: 'JQ-8F2K9',
        url: 'https://www.jetstar.com/',
        cost: { amount: 629, currency: 'AUD' },
      },
      {
        id: 'bk-2',
        kind: 'flight',
        name: '回程 KIX → MEL',
        status: 'paid',
        date: '2026-10-04',
        confirmation: 'JQ-8F2K9',
        cost: { amount: 641, currency: 'AUD' },
      },
      {
        id: 'bk-3',
        kind: 'hotel',
        name: 'Hotel Gracery Shinjuku × 3',
        status: 'paid',
        date: '2026-09-25',
        cost: { amount: 804, currency: 'AUD' },
      },
      {
        id: 'bk-4',
        kind: 'hotel',
        name: 'Kyoto Resol × 3',
        status: 'booked',
        date: '2026-09-29',
        cost: { amount: 594, currency: 'AUD' },
      },
      {
        id: 'bk-5',
        kind: 'hotel',
        name: '大阪 Cross Hotel × 2',
        status: 'need',
        date: '2026-10-02',
      },
      {
        id: 'bk-6',
        kind: 'activity',
        name: 'Shibuya Sky',
        status: 'paid',
        date: '2026-09-26',
        cost: { amount: 36, currency: 'AUD' },
      },
      {
        id: 'bk-7',
        kind: 'activity',
        name: '清水寺 / 金阁寺 / 大阪城',
        status: 'need',
      },
      {
        id: 'bk-8',
        kind: 'rental-car',
        name: '富士自驾 1 天',
        status: 'paid',
        cost: { amount: 186, currency: 'AUD' },
      },
      {
        id: 'bk-9',
        kind: 'activity',
        name: 'TeamLab Planets（备选）',
        status: 'need',
      },
    ],
    budget: [
      { id: 'b1', name: '机票', estimated: 1400, booked: 1270, paid: 1270 },
      { id: 'b2', name: '住宿', estimated: 1600, booked: 1398, paid: 804 },
      { id: 'b3', name: '餐饮', estimated: 1200, booked: 0, paid: 0 },
      { id: 'b4', name: '交通', estimated: 520, booked: 186, paid: 186 },
      { id: 'b5', name: '活动', estimated: 480, booked: 36, paid: 36 },
      { id: 'b6', name: '购物', estimated: 600, booked: 0, paid: 0 },
      { id: 'b7', name: '伴手礼', estimated: 300, booked: 0, paid: 0 },
      { id: 'b8', name: '其他', estimated: 200, booked: 0, paid: 0 },
      { id: 'b9', name: '应急', estimated: 700, booked: 0, paid: 0 },
    ],
    expenses: [
      {
        id: 'ex-1',
        title: '去程机票',
        amount: 1258,
        currency: 'AUD',
        category: '机票',
        date: '2026-06-21',
        paidBy: 'm-a',
        split: 'equal',
        excluded: [],
        status: 'paid',
      },
      {
        id: 'ex-2',
        title: '新宿酒店',
        amount: 804,
        currency: 'AUD',
        category: '住宿',
        date: '2026-07-02',
        paidBy: 'm-a',
        split: 'equal',
        excluded: [],
        status: 'paid',
      },
      {
        id: 'ex-3',
        title: 'Shibuya Sky 门票',
        amount: 36,
        currency: 'AUD',
        category: '活动',
        date: '2026-08-11',
        paidBy: 'm-b',
        split: 'equal',
        excluded: [],
        status: 'paid',
      },
    ],
    gifts: [
      { id: 'g1', forWhom: '妈妈', item: '抹茶和菓子', city: 'Kyoto', status: 'need' },
      { id: 'g2', forWhom: '同事', item: 'KitKat 组合', city: 'Tokyo', status: 'need' },
      { id: 'g3', forWhom: '朋友 A', item: '狐狸御守', city: 'Kyoto', status: 'need' },
    ],
    notes:
      '两个人的第一次日本。节奏不要排太满。京都 9/30 大概率下雨，Plan B 已经备好。',
    share: { visibility: 'friends' },
    createdAt: '2026-04-12',
  }
}

export function oceanRoadTrip(): Trip {
  return {
    id: 'template-gor',
    name: 'Great Ocean Road',
    origin: 'Melbourne',
    destinations: ['Lorne', 'Apollo Bay', 'Port Campbell'],
    startDate: '2026-11-06',
    endDate: '2026-11-09',
    travellers: 2,
    members: [{ id: 'm-a', name: 'You', role: 'owner', color: '#4F6F52' }],
    budgetPerPerson: 900,
    totalBudget: 1800,
    homeCurrency: 'AUD',
    theme: 'forest',
    cover: 'ocean-road',
    transportModes: ['self-drive'],
    template: true,
    days: [
      {
        id: uid(),
        date: '2026-11-06',
        city: 'Lorne',
        stay: 'Lorne Hotel',
        transportMode: 'self-drive',
        weather: w('sunny', 14, 22, 10),
        activePlan: 'A',
        planA: [
          p({
            name: 'Melbourne 出发',
            category: '交通',
            setting: 'mixed',
            time: '08:00',
            transportToNext: 'self-drive',
            coords: { lat: -37.8136, lng: 144.9631 },
          }),
          p({
            name: 'Lorne 小镇',
            category: '景点',
            setting: 'outdoor',
            time: '11:00',
            notes: 'Recommended stop · +8 min · ⭐ 4.7 · 停留 45 min',
            coords: { lat: -38.536, lng: 143.975 },
          }),
          p({
            name: 'Apollo Bay',
            category: '住宿',
            setting: 'mixed',
            time: '16:00',
            coords: { lat: -38.755, lng: 143.669 },
          }),
        ],
        planB: [],
      },
      {
        id: uid(),
        date: '2026-11-07',
        city: 'Port Campbell',
        stay: 'Port Campbell',
        transportMode: 'self-drive',
        weather: w('wind', 12, 18, 30),
        activePlan: 'A',
        planA: [
          p({
            name: 'Twelve Apostles',
            category: '景点',
            setting: 'outdoor',
            time: '10:00',
            priority: 'must',
            coords: { lat: -38.665, lng: 143.104 },
          }),
          p({
            name: 'Loch Ard Gorge',
            category: '景点',
            setting: 'outdoor',
            time: '12:00',
            coords: { lat: -38.647, lng: 143.072 },
          }),
        ],
        planB: [
          p({
            name: 'Apollo Bay 咖啡馆躲风',
            category: '餐饮',
            setting: 'indoor',
            time: '10:00',
          }),
        ],
      },
    ],
    saved: [],
    compares: [],
    bookings: [],
    budget: BUDGET_EMPTY(1800),
    expenses: [],
    gifts: [],
    notes: '自驾示范：沿途 Smart Stop（Lorne）可以直接加入路线。',
    share: { visibility: 'public' },
    createdAt: '2026-01-01',
  }
}

function BUDGET_EMPTY(total: number) {
  const names = ['机票', '住宿', '餐饮', '交通', '活动', '购物', '伴手礼', '其他', '应急']
  return names.map((name, i) => ({
    id: `b${i}`,
    name,
    estimated: i === 8 ? Math.round(total * 0.1) : 0,
    booked: 0,
    paid: 0,
  }))
}

export function emptyBudget(total: number) {
  return BUDGET_EMPTY(total)
}

export function baliTrip(): Trip {
  return {
    id: 'template-bali',
    name: 'Bali Slow Week',
    origin: 'Melbourne',
    destinations: ['Canggu', 'Ubud'],
    startDate: '2026-05-10',
    endDate: '2026-05-17',
    travellers: 2,
    members: [{ id: 'm-a', name: 'You', role: 'owner', color: '#3E8EBE' }],
    budgetPerPerson: 2200,
    totalBudget: 4400,
    homeCurrency: 'AUD',
    theme: 'ocean',
    cover: 'bali',
    transportModes: ['taxi', 'walking'],
    template: true,
    days: [
      {
        id: uid(),
        date: '2026-05-10',
        city: 'Canggu',
        stay: 'Echo Beach',
        transportMode: 'taxi',
        weather: w('sunny', 24, 31, 20),
        activePlan: 'A',
        planA: [
          p({
            name: 'Echo Beach 日落',
            category: '景点',
            setting: 'outdoor',
            time: '17:30',
            coords: { lat: -8.655, lng: 115.135 },
          }),
        ],
        planB: [
          p({
            name: '咖啡馆躲雷阵雨',
            category: '餐饮',
            setting: 'indoor',
            time: '16:00',
          }),
        ],
      },
    ],
    saved: [],
    compares: [],
    bookings: [],
    budget: BUDGET_EMPTY(4400),
    expenses: [],
    gifts: [],
    notes: '慢节奏。下午雷阵雨几乎天天有，户外活动尽量上午。',
    share: { visibility: 'public' },
    createdAt: '2026-01-01',
  }
}
